### ISSUE TITLE
 'module' object has no attribute 'Tracer'

### ISSUE THREAD

**Issue by carterMgj** [shellphish/rex#17]
Hi, I run rex and meet the blow problem:

#---------------------------------------------------------------------------------------
>>> crash=rex.Crash('./test','a'*1024)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rex/crash.py", line 108, in __init__
    self._tracer = tracer.Tracer(binary, input=self.crash, pov_file=self.pov_file, resiliency=False,
AttributeError: 'module' object has no attribute 'Tracer'

#---------------------------------------------------------------------------------------
      I install tracer according to 2 methods:
- pip install tracer                  ( tracer 0.3.2)
- it clone https://github.com/angr/tracer  & python setup.py install

     Please help me, thanks !

**Comment by zardus** [comment]
Please save yourself some sanity and use the docker container: `docker run -it shellphish/mechaphish`. If you _really_ want to do the manual install, check out what the dockerfile does (at github.com/mechaphish/setup).
