### ISSUE TITLE
cannot import name TracerPoV

### ISSUE THREAD

**Issue by b0q1** [shellphish/rex#30]
WARNING | 2018-11-21 12:25:05,282 | angr.analyses.disassembly_utils | Your version of capstone does not support MIPS instruction groups.
Traceback (most recent call last):
  File "test_rex.py", line 8, in <module>
    import rex
  File "/usr/local/lib/python2.7/dist-packages/rex/__init__.py", line 2, in <module>
    from rex.crash import Crash, QuickCrash, NonCrashingInput
  File "/usr/local/lib/python2.7/dist-packages/rex/crash.py", line 14, in <module>
    from tracer import TracerPoV
ImportError: cannot import name TracerPoV

**Comment by rhelmot** [comment]
"tracer" should not be the package you get when you say `pip install tracer`. You need to install [https://github.com/angr/tracer](angr's tracer package).

**Comment by b0q1** [comment]
@rhelmot thx

**Comment by Bearshanjun** [comment]
from rex import NonCrashingInput, QuickCrash
ImportError: cannot import name 'QuickCrash'

I can't find QuickCrash in the folder.It was deleted or moved yet?

**Comment by rhelmot** [comment]
QuickCrash doesn't exist anymore. It only worked on CGC binaries to begin with.

Also please make new issues instead of piggybacking on a separate issue which is completely different.
