### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by yangshouguo** [shellphish/rex#38]
when i tried to run test_rex.py script i got the problem "FileNotFoundError: [Errno 2] No such file or directory: '/home/ysg/WorkSpace/AEG/rex/tests/../../binaries/tests/i386/arbitrary_transmit'", can you provide the test binary file ?

**Comment by rhelmot** [comment]
All the test files are in the angr/binaries repository. This is the case for all tests in all the angr repositories.

**Comment by yangshouguo** [comment]
> All the test files are in the angr/binaries repository. This is the case for all tests in all the angr repositories.

thx!
