### ISSUE TITLE
cai i find any document for using the rex

### ISSUE THREAD

**Issue by yangshouguo** [shellphish/rex#40]
I am fresh man in AEG, please provide a document for the project or tell me a url to know how rex works.

**Comment by Ma3k4H3d** [comment]
read paper & code

**Comment by adamdoupe** [comment]
Currently there is no documentation in using rex. For now, the code is the documentation. 

Once it's more stable we will have documentation.

**Comment by ltfish** [comment]
> please provide a document for the project or tell me a url to know how rex works.

Note that it is not our priority to provide documentation. This is an open source project and everything is provided "as it is". I feel it is an English problem, but if it's not, the way you state your request makes me feel insulted.

**Comment by yangshouguo** [comment]
I am so sorry to use the wrong words. I just want to have a quick understand about rex.
