### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Manouchehri** [shellphish/rex#5]
Getting rex set up is still somewhat rough, should we add an install guide here or stick with https://github.com/mechaphish/mecha-docs? Either way, it should be linked to in the `REAME.md`.

(re: email from @Owlz)

> Hey David,
> 
> Not a VM specifically for it. I do recall having many-a-issue on it. Two things, the first is the correct (or at least required at the time) order of installing packages to get it to install:
> 
> https://github.com/shellphish/shellphish-qemu.git
> 
> https://github.com/mechaphish/povsim.git
> 
> https://github.com/salls/angrop.git
> 
> https://github.com/mechaphish/compilerex.git
> 
> https://github.com/shellphish/rex.git
> 
> https://github.com/angr/tracer
> 
> https://github.com/shellphish/shellphish-afl.git
> ---
> 
> The second, I have a bash script that will install/compile all of Mechaphish reliably. This would probably be overkill for what you're asking, but you can likely remove unwanted components from the install line and it should still give you a working rex copy. It basically boils down to these two lines (with some bash in-between):
> 
> sudo apt-get update
> sudo apt-get install -y virtualenvwrapper python2.7-dev build-essential sudo libxml2-dev libxslt1-dev git libffi-dev cmake libreadline-dev libtool debootstrap debian-archive-keyring libglib2.0-dev libpixman-1-dev libpq-dev python-dev libc6:i386 libncurses5:i386 libstdc++6:i386 zlib1g:i386 pkg-config zlib1g-dev libtool libtool-bin wget automake autoconf coreutils bison libacl1-dev qemu-user qemu-kvm socat postgresql-client nasm binutils-multiarch llvm clang
> 
> git clone https://github.com/angr/angr-dev.git $MechaPhishDIR
> 
> cd $MechaPhishDIR
> 
> ./setup.sh -p mechaphish -r https://github.com/shellphish -r https://github.com/mechaphish -r https://github.com/salls -D \
>                 ana idalink cooldict mulpyplexer monkeyhex superstruct \
>                 shellphish-afl shellphish-qemu capstone unicorn peewee \
>                 archinfo vex pyvex cle claripy simuvex angr angr-management angr-doc \
>                 binaries identifier fidget angrop tracer fuzzer driller \
>                 compilerex povsim rex farnsworth patcherex colorguard \
>                 common-utils network_poll_creator patch_performance \
>                 worker meister ambassador scriba virtual-competition manual-interaction

**Comment by Owlz** [comment]
I've had to update that setup.sh line to remove unicorn given recent changes. unicorn can be pip installed now.

**Comment by XMGH-z** [comment]
Thank you !
