### ISSUE TITLE
AttributeError: module 'keystone' has no attribute 'KS_ARCH_X86'

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [shellphish/rex#55]
Hello while trying to import rex I got this error 

python Python 3.7.5
Parrot OS
Linux parrot 5.3.0-3parrot3-amd64 #1 SMP Parrot 5.3.9-3parrot3 (2019-11-23) x86_64 GNU/Linux

P.S. Sorry I haven't been responding. Life got in the way.

**Comment by rhelmot** [comment]
have you perhaps accidentally installed `keystone` instead of `keystone-engine`?

**Comment by KittyTechnoProgrammer** [comment]
*sudo pip3 uninstall keystone*
WARNING: Skipping keystone as it is not installed.

Then I pip3 installed keystone-engine 
*sudo pip3 install keystone-engine*

then it worked. Was most likely fighting with the other keystone library. 

Thank you. You have made a great tool. 

Suggest : Put a try and except to catch this error, and make a note to the user to make sure that they have the right keystone library. Would you like a PR?

P.S. I uploaded the file ya'll wanted on the other issue.

**Comment by KittyTechnoProgrammer** [comment]
Would you like me to close this issue?

**Comment by rhelmot** [comment]
Yeah, that would be a good PR. it should probably go in `archinfo`, since that's the lowest level thing which will add the check to anything that depends on it.

I'll get to your other issue eventually. Tracing issues are hard to debug :(

**Comment by davidhcefx** [comment]
### Some suggestions on removing pip packages
`keystone` installs **A LOT OF** dependencies, and you might probably want all of them to be removed.
Unfortunately, `pip` was not capable of [removing dependencies automatically](https://stackoverflow.com/questions/7915998/does-uninstalling-a-package-with-pip-also-remove-the-dependent-packages), so I would suggest to run:
```sh
pip-autoremove -y keystone
```
In case that `pip-autoremove` sometimes failed, you can run this instead:
```sh
pip-autoremove -y oslo.messaging oslo.middleware oslo.policy oslo.upgradecheck oslo.db osprofiler oauthlib keystonemiddleware passlib pyJWT pysaml2 scrypt
```
which is what I eventually run.
